apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: mshell-dev-com-tls
spec:
  acme:
    config:
      - domains:
          - mshell-dev.com
          - www.mshell-dev.com
        http01:
          ingressClass: nginx
  commonName: mshell-dev.com
  dnsNames:
    - mshell-dev.com
    - www.mshell-dev.com
  issuerRef: letsencrypt-prod
  kind: ClusterIssuer
  secretName: mshell-dev-com
