apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: mshell-dev-com-tls
spec:
  secretName: mshell-dev-com
  issuerRef: letsencrypt-prod
  kind: ClusterIssuer
commonName: mshell-dev.com
dnsNames:
  - mshell-dev.com
  - www.mshell-dev.com
acme:
  confit:
    - http01:
        ingressClass: nginx
      domains:
        - mshell-dev.com
        - www.mshell-dev.com
